export function stripColors(str: string) {
   
    return str.replaceAll("^^11", "^1")
    .replaceAll("^^22", "")
    .replaceAll("^^33", "")
    .replaceAll("^^44", "")
    .replaceAll("^^55", "")
    .replaceAll("^^66", "")
    .replaceAll("^^77", "")
    .replaceAll("^^88", "")
    .replaceAll("^^99", "")
    .replaceAll("^^00", "")
    .replaceAll("^1", "")
    .replaceAll("^2", "")
    .replaceAll("^3", "")
    .replaceAll("^4", "")
    .replaceAll("^5", "")
    .replaceAll("^6", "")
    .replaceAll("^7", "")
    .replaceAll("^8", "")
    .replaceAll("^9", "")
    .replaceAll("^0", "")
}